language: ruby
cache: bundler

sudo: false

branches:
  only:
    - master

# Early warning system to catch if Rubygems breaks something
before_install:
  - gem update --system

rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
