AllCops:
  Exclude:
    - vendor/**/*
    - Guardfile

AlignParameters:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
Style/FileName:
  Enabled: false
Style/Alias:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
PerceivedComplexity:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

# https://github.com/chef/cookstyle/pull/5
Style/TrailingCommaInLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

# Underscores in numbers are unnecessary, especially for port numbers where they are unexpected
Style/NumericLiterals:
  Enabled: false

# regex rules often trigger no matter what you do with inspec/serverspec matchers
Style/RegexpLiteral:
  Exclude:
    - 'test/**/*'

# some names are not ascii and this prevents copyright comments
Style/AsciiComments:
  Enabled: false
